version: "3.9"
services:
  app:
    restart: on-failure 
    build:
      args:
        - BuildMode=production
    volumes:
      - ./apps/backend/src/db/migrations:/usr/app/apps/backend/src/db/migrations
    env_file:
      - .env.production
    command: "pnpm turbo run migration:gen"