version: "3.9"
services:
  nginx:
    ports:
      - "8443:443"
      - "8080:80"
  app:
    build:
      args:
        - BuildMode=development
    env_file:
      - .env.development
    volumes:
      - ./apps:/usr/app/apps
      - ./packages:/usr/app/packages
    command: pnpm turbo run dev
 