version: "3.9"
services:
  nginx:
    ports:
      - "8443:443"
      - "8080:80"
  app:
    build:
      args:
        - BuildMode=development
    env_file:
      - ./app/backend/.env.development
    volumes:
      - ./app/backend:/usr/app
      - ./app/backend/dist:/usr/app/dist
      - ./usr/app/node_modules
      - ./app/frontend:/usr/app
      - ./app/frontend/.next:/usr/app/.next
    # command: yarn turbo run dev
    