version: "3.9"
services:
  backend:
    restart: "no"
    build:
      args:
        - BuildMode=production
    volumes:
      - ./packages/backend/src/db/migrations:/usr/app/src/db/migrations
    env_file:
      - ./packages/backend/.env.production
    command: "yarn migration:gen"