version: "3.9"
services:
  nginx:
    ports:
      - "8443:443"
      - "8080:80"
  app:
    build:
      args:
        - BuildMode=development
    env_file:
      - .env.development
    volumes:
      - ./apps/backend:/usr/app/apps/backend
      - ./apps/backend/dist:/usr/app/apps/backend/dist
      - ./apps/frontend:/usr/app/apps/frontend
      - ./apps/frontend/.next:/usr/app/apps/frontend/.next
    command: yarn turbo run build
 