version: "3"
services:
  database:
    image: postgres:latest
    # TODO: Change password
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: GoBot
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: gobot/backend
    build:
      context: ./packages/backend
    depends_on:
      - database
    ports:
      - "4000:4000"
  frontend:
    image: gobot/frontend
    build:
      context: ./packages/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    
