version: "3.9"
services:
  nginx:
    ports:
      - "3000:443"
      - "4000:8443"
    volumes:
      - "./nginx/logs:/var/log/nginx"
  backend:
    build:
      args:
        - BuildMode=development
    env_file:
      - ./packages/backend/.env.development
    volumes:
      - ./packages/backend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    command: yarn dev
  frontend:
    build:
      args:
        - BuildMode=development
    volumes:
      - ./packages/frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    command: yarn dev
    
