version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/nginx/ssl"
    depends_on:
      - app 
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  postgres:
    image: postgres:latest
    user: $DOCKER_USER
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/clusters/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  pgbackup:
    image: prodrigestivill/postgres-backup-local
    user: $DOCKER_USER
    restart: always
    volumes:
      - ./data/backups/pgbackup:/backups
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${DB_NAME} 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
  redis:
    image: redis:latest
    user: $DOCKER_USER
    restart: always
    volumes:
      - ./data/clusters/redisdata:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis ping"]
      interval: 5s
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  app:
    image: gobot
    build: .
    expose:
      - 3000
      - 4000
    depends_on:
      - postgres
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10