version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/nginx/ssl"
    depends_on:
      - backend
      - frontend
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./packages/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: gobot/backend
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: ./Dockerfile
    expose:
      - 4000
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: gobot/frontend
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: ./Dockerfile
    expose:
      - 3000
