version: "3.9"
services:
  database:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s
  backend:
    build:
      args:
        - BuildMode=production
    ports:
      - 8080:4000
      - 8443:4000
    env_file:
      - ./packages/backend/.env.production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s
  frontend:
    build:
      args:
        - BuildMode=production  
    ports:
      - 80:3000
      - 443:3000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s