version: "3"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./packages/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: gobot/backend
    build:
      context: ./packages/backend 
      dockerfile: ./Dockerfile
    depends_on: 
      database:
        condition: service_healthy
    ports:
      - "4000:4000"
  frontend:
    image: gobot/frontend
    build:
      context: ./packages/frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"