version: "3.9"
services:
  app:
    restart: on-failure 
    build:
      args:
        - BuildMode=production
    volumes:
      - ./app/backend/src/db/migrations:/usr/app/src/db/migrations
    env_file:
      - ./app/backend/.env.production
    command: "yarn backend migration:run"