version: "3.9"
services:
  backend:
    build:
      args:
        - BuildMode=development
    env_file:
      - ./packages/backend/.env.development
    volumes:
      - ./packages/backend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    command: yarn dev
    ports:
      - 4000:4000
  frontend:
    build:
      args:
        - BuildMode=development
    volumes:
      - ./packages/frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    command: yarn dev
    ports:
      - 3000:3000
