version: "3.9"
services:
  database:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s
  backend:
    build:
      args:
        - BuildMode=production
    env_file:
      - ./packages/backend/.env.production
    dns:
      - 1.1.1.1
      - 1.0.0.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s
  frontend:
    build:
      args:
        - BuildMode=production  
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 443:3000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s