version: "3.9"
services:
  nginx:
    ports:
      - "8443:443"
      - "8080:80"
  app:
    build:
      args:
        - BuildMode=development
    env_file:
      - .env.development
    volumes:
      - ./apps/backend:/usr/app/apps/backend
      - ./apps/backend/dist:/usr/app/apps/backend/dist
      - ./apps/frontend:/usr/app/apps/frontend
      - ./apps/frontend/.next:/usr/app/apps/frontend/.next
      - ./packages/api/dist:/usr/app/packages/api/dist
      - ./packages/database/dist:/usr/app/packages/database/dist
      - ./packages/discord/dist:/usr/app/packages/discord/dist
      - ./packages/environment/dist:/usr/app/packages/environment/dist
      - ./packages/logger/dist:/usr/app/packages/logger/dist
    command: yarn turbo run dev
 