version: "3"
services:
  database:
    image: gobot-database 
    environment:
      # - DB_PORT=${DB_PORT}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./database:/var/lib/gobotdb/data
    ports:
      - 5432:5432
  backend:
    image: gobot-backend
    build:
      context: ./packages/backend
    depends_on:
      - database
    ports:
      - "4000:4000"
  frontend:
    image: gobot-frontend
    build:
      context: ./packages/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    
