version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/nginx/ssl"
    depends_on:
      - backend
      - frontend
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./packages/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./packages/redisdata:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h redis ping"]
      interval: 5s
  backend:
    image: gobot/backend
    build:
      context: ./packages/backend
      dockerfile: ./Dockerfile
    expose:
      - 4000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  frontend:
    image: gobot/frontend
    build:
      context: ./packages/frontend
      dockerfile: ./Dockerfile
    expose:
      - 3000
    depends_on:
      - backend
