name: Copy development files
on:
  push:
    branches: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr
          path: /
          remote_path: /root/dev/gobot
          remote_host: ${{ secrets.GOBOT_SSH_HOST }}
          remote_user: ${{ secrets.GOBOT_SSH_USER }}
          remote_key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}