name: Copy development files
on:
  push:
    branches: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /root/dev/gobot
          remote_host: ${{ secrets.GOBOT_SSH_HOST }}
          remote_user: ${{ secrets.GOBOT_SSH_USER }}
          remote_key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GOBOT_SSH_HOST }}
          username: ${{ secrets.GOBOT_SSH_USER }}
          key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GOBOT_SSH_PORT }}
          script: |
            cp /root/env/.env.development /root/dev/gobot/packages/backend/.env.development