name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Copy Data
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GOBOT_SSH_HOST }}
          username: ${{ secrets.GOBOT_SSH_USER }}
          key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GOBOT_SSH_PORT }}
          script: |
            cp -r /root/app/gobot/data /root/app/
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /root/app/gobot
          remote_host: ${{ secrets.GOBOT_SSH_HOST }}
          remote_user: ${{ secrets.GOBOT_SSH_USER }}
          remote_key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GOBOT_SSH_HOST }}
          username: ${{ secrets.GOBOT_SSH_USER }}
          key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GOBOT_SSH_PORT }}
          script: |
            cp -r /root/app/data /root/app/gobot
            cp /root/secrets/env/.env.production /root/app/gobot/packages/backend/.env.production
            cp -r /root/secrets/ssl /root/app/gobot/ssl
            cd /root/app/gobot/
            sudo yarn stop:prod
            sudo yarn migration:run
            sudo yarn build:prod --no-cache
            sudo yarn deploy -d