name: remote ssh command
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.GOBOT_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: /
          remote_path: /root/app/gobot
          remote_host: ${{ secrets.GOBOT_SSH_HOST }}
          remote_user: ${{ secrets.GOBOT_SSH_USER }}
          remote_key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GOBOT_SSH_HOST }}
          username: ${{ secrets.GOBOT_SSH_USER }}
          key: ${{ secrets.GOBOT_SSH_PRIVATE_KEY }}
          port: ${{ secrets.GOBOT_SSH_PORT }}
          script: |
            whoami
            cd /root/app/gobot/
            ls -al
            yarn docker:start -d
